name: Deploy to Firebase Hosting on Commit

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '.github/workflows/firebase-hosting-commit.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'firebase.json'
      - 'firestore.rules'


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache and install firebase-tools
        uses: actions/cache@v4
        id: cache-firebase-tools
        with:
          path: ~/.npm/_npx/
          key: ${{ runner.os }}-firebase-tools-${{ hashFiles('package.json') }}
      - if: steps.cache-firebase-tools.outputs.cache-hit != 'true'
        name: Install firebase-tools (if not cached)
        run: npm install -g firebase-tools

      - name: Build project
        run: pnpm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WALDORFWAHLEN }}
          channelId: live
          projectId: waldorfwahlen
          target: waldorfwahlen