name: Deploy to Firebase Hosting on Commit

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '.github/workflows/firebase-hosting-commit.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: pnpm firebase deploy --only hosting --project waldorfwahlen --json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WALDORFWAHLEN }}