name: Deploy to Firebase Hosting on Commit

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '.github/workflows/firebase-hosting-commit.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable corepack (for pnpm)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WALDORFWAHLEN }}
          channelId: live
          projectId: waldorfwahlen
