name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache and install firebase-tools
        uses: actions/cache@v4
        id: cache-firebase-tools
        with:
          path: ~/.npm/_npx/
          key: ${{ runner.os }}-firebase-tools-${{ hashFiles('package.json') }}
      - if: steps.cache-firebase-tools.outputs.cache-hit != 'true'
        name: Install firebase-tools (if not cached)
        run: npm install -g firebase-tools

      - name: Build project
        env:
          VITE_APP_CHECK_DEBUG_TOKEN_FROM_CI: ${{ secrets.VITE_APP_CHECK_DEBUG_TOKEN_FROM_CI }}
        run: pnpm run build

      - name: Deploy to Firebase Hosting Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WALDORFWAHLEN }}
          projectId: waldorfwahlen
